// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package scheduledactions

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPendingAuthorPostPublication = `-- name: CancelPendingAuthorPostPublication :many
UPDATE scheduled_actions
SET state = 'cancelled'
WHERE origin = 'author'
  AND action = 'change_state'
  AND target_kind = 'post'
  AND target_id = $1
  AND created_by = $2
  AND state = 'pending'
RETURNING id, action, target_kind, target_id, params, scheduled_for,
          state, error, created_by, created_at, executed_at, origin
`

type CancelPendingAuthorPostPublicationParams struct {
	TargetID  string `json:"target_id"`
	CreatedBy *int64 `json:"created_by"`
}

// Cancels the caller's own pending author schedule for the post and
// returns what it cancelled (zero rows = nothing pending). Guarded on
// origin AND created_by, so a row somebody else made is invisible to
// this statement even when it targets the same post.
func (q *Queries) CancelPendingAuthorPostPublication(ctx context.Context, arg CancelPendingAuthorPostPublicationParams) ([]ScheduledAction, error) {
	rows, err := q.db.Query(ctx, cancelPendingAuthorPostPublication, arg.TargetID, arg.CreatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledAction
	for rows.Next() {
		var i ScheduledAction
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.TargetKind,
			&i.TargetID,
			&i.Params,
			&i.ScheduledFor,
			&i.State,
			&i.Error,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExecutedAt,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelScheduledAction = `-- name: CancelScheduledAction :execrows
UPDATE scheduled_actions
SET state = 'cancelled'
WHERE id = $1 AND state = 'pending'
`

// Only a PENDING action can be cancelled — a done/failed/cancelled one
// is terminal. Guarding on state='pending' makes cancel idempotent and
// lets the handler map rows-affected=0 to "not cancellable" rather than
// silently succeeding on an already-fired action.
func (q *Queries) CancelScheduledAction(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelScheduledAction, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimDueAction = `-- name: ClaimDueAction :one
SELECT id, action, target_kind, target_id, params, scheduled_for,
       state, error, created_by, created_at, executed_at, origin
FROM scheduled_actions
WHERE state = 'pending' AND scheduled_for <= NOW()
ORDER BY scheduled_for ASC
FOR UPDATE SKIP LOCKED
LIMIT 1
`

// The reaper's claim. One pending action whose time has come, oldest
// first, row-locked so overlapping reaper runs never grab the same one.
// SKIP LOCKED means a second reaper moves on to the next due action
// instead of blocking. The caller executes + marks within the SAME
// transaction that holds this lock, so no intermediate "executing"
// state is needed.
func (q *Queries) ClaimDueAction(ctx context.Context) (ScheduledAction, error) {
	row := q.db.QueryRow(ctx, claimDueAction)
	var i ScheduledAction
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.TargetKind,
		&i.TargetID,
		&i.Params,
		&i.ScheduledFor,
		&i.State,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExecutedAt,
		&i.Origin,
	)
	return i, err
}

const countDueActions = `-- name: CountDueActions :one
SELECT COUNT(*)::bigint AS value
FROM scheduled_actions
WHERE state = 'pending' AND scheduled_for <= NOW()
`

// Cheap "is there work" probe for the reaper's log line + tests.
func (q *Queries) CountDueActions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDueActions)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const createAuthorPostPublication = `-- name: CreateAuthorPostPublication :one

INSERT INTO scheduled_actions (action, target_kind, target_id, params, scheduled_for, created_by, origin)
VALUES ('change_state', 'post', $1, $2, $3, $4, 'author')
RETURNING id, action, target_kind, target_id, params, scheduled_for,
          state, error, created_by, created_at, executed_at, origin
`

type CreateAuthorPostPublicationParams struct {
	TargetID     string             `json:"target_id"`
	Params       []byte             `json:"params"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	CreatedBy    *int64             `json:"created_by"`
}

// ---------------------------------------------------------------------------
// The author seam (#1119 sprint 21e). An author's own publication
// schedule is an ordinary change_state/post row with origin = 'author';
// every query here is scoped to that origin AND to the row's creator,
// so this surface can neither see nor touch an operator's or the
// system's instruction for the same post. See migration 00069 for the
// partial unique index that keeps one pending author row per post.
// ---------------------------------------------------------------------------
// Inserts the author's standing instruction. The unique index
// scheduled_actions_author_pending_post_idx raises 23505 when another
// pending author row for the post exists; the Store maps that to
// ErrAuthorScheduleConflict rather than checking first.
func (q *Queries) CreateAuthorPostPublication(ctx context.Context, arg CreateAuthorPostPublicationParams) (ScheduledAction, error) {
	row := q.db.QueryRow(ctx, createAuthorPostPublication,
		arg.TargetID,
		arg.Params,
		arg.ScheduledFor,
		arg.CreatedBy,
	)
	var i ScheduledAction
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.TargetKind,
		&i.TargetID,
		&i.Params,
		&i.ScheduledFor,
		&i.State,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExecutedAt,
		&i.Origin,
	)
	return i, err
}

const createScheduledAction = `-- name: CreateScheduledAction :one


INSERT INTO scheduled_actions (action, target_kind, target_id, params, scheduled_for, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, action, target_kind, target_id, params, scheduled_for,
          state, error, created_by, created_at, executed_at, origin
`

type CreateScheduledActionParams struct {
	Action       string             `json:"action"`
	TargetKind   string             `json:"target_kind"`
	TargetID     string             `json:"target_id"`
	Params       []byte             `json:"params"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	CreatedBy    *int64             `json:"created_by"`
}

// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Kenneth Blossom
// Scheduled-action engine queries (#40 sprint 1, ADR 0020).
// Schedules one action. created_by is nullable — a system-scheduled
// action (e.g. trash retention) has no user behind it.
func (q *Queries) CreateScheduledAction(ctx context.Context, arg CreateScheduledActionParams) (ScheduledAction, error) {
	row := q.db.QueryRow(ctx, createScheduledAction,
		arg.Action,
		arg.TargetKind,
		arg.TargetID,
		arg.Params,
		arg.ScheduledFor,
		arg.CreatedBy,
	)
	var i ScheduledAction
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.TargetKind,
		&i.TargetID,
		&i.Params,
		&i.ScheduledFor,
		&i.State,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExecutedAt,
		&i.Origin,
	)
	return i, err
}

const execAssetChangeSensitivity = `-- name: ExecAssetChangeSensitivity :one

WITH prev AS (
    SELECT assets.id AS pid, assets.sensitivity AS old_sensitivity
    FROM assets
    WHERE assets.id = $1 AND assets.deleted_at IS NULL
    FOR UPDATE
)
UPDATE assets a
SET sensitivity = $2, updated_at = NOW()
FROM prev
WHERE a.id = prev.pid
RETURNING prev.old_sensitivity::text AS old_sensitivity
`

type ExecAssetChangeSensitivityParams struct {
	ID          pgtype.UUID `json:"id"`
	Sensitivity string      `json:"sensitivity"`
}

// ---------------------------------------------------------------------------
// Executor domain writes. These live in the executor's own package on
// purpose: the scheduled-action engine owns the small, audited mutations
// it performs, and each is a single guarded statement.
// ---------------------------------------------------------------------------
// Flips an asset's sensitivity tier and returns the PREVIOUS value so
// the executor can record old->new in the audit trail. The CTE reads +
// locks the row before the UPDATE so the returned old value is the real
// prior tier, not the just-written one. Zero rows = asset missing or
// soft-deleted; the executor treats that as a failure, not a silent
// no-op.
func (q *Queries) ExecAssetChangeSensitivity(ctx context.Context, arg ExecAssetChangeSensitivityParams) (string, error) {
	row := q.db.QueryRow(ctx, execAssetChangeSensitivity, arg.ID, arg.Sensitivity)
	var old_sensitivity string
	err := row.Scan(&old_sensitivity)
	return old_sensitivity, err
}

const execAssetChangeState = `-- name: ExecAssetChangeState :one
WITH prev AS (
    SELECT assets.id AS pid, assets.state_id AS old_state_id
    FROM assets
    WHERE assets.id = $1 AND assets.deleted_at IS NULL
    FOR UPDATE
)
UPDATE assets a
SET state_id = $2, updated_at = NOW()
FROM prev
WHERE a.id = prev.pid
RETURNING prev.old_state_id AS old_state_id
`

type ExecAssetChangeStateParams struct {
	ID      pgtype.UUID `json:"id"`
	StateID pgtype.UUID `json:"state_id"`
}

// Moves an asset to a workflow state, returning the previous state_id
// for the audit trail. Same CTE-lock pattern as sensitivity.
func (q *Queries) ExecAssetChangeState(ctx context.Context, arg ExecAssetChangeStateParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, execAssetChangeState, arg.ID, arg.StateID)
	var old_state_id pgtype.UUID
	err := row.Scan(&old_state_id)
	return old_state_id, err
}

const execAssetSoftDelete = `-- name: ExecAssetSoftDelete :execrows
UPDATE assets
SET deleted_at = NOW(), deleted_reason = $2, deleted_by_user_ref = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type ExecAssetSoftDeleteParams struct {
	ID               pgtype.UUID `json:"id"`
	DeletedReason    *string     `json:"deleted_reason"`
	DeletedByUserRef *int64      `json:"deleted_by_user_ref"`
}

// Soft-delete (set deleted_at); the nightly GC hard-deletes later. Only
// acts on a live row, so re-running against an already-deleted asset is
// a no-op the executor reports as rows-affected=0.
//
// deleted_by_user_ref is the scheduled action's `created_by`, which is
// itself nullable — a system-scheduled retention delete has no human
// behind it. NULL there means "nobody may self-restore this", which is
// the correct fail-closed answer rather than a gap (#931).
func (q *Queries) ExecAssetSoftDelete(ctx context.Context, arg ExecAssetSoftDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, execAssetSoftDelete, arg.ID, arg.DeletedReason, arg.DeletedByUserRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssetSensitivityDomain = `-- name: GetAssetSensitivityDomain :one
SELECT owner_user_ref, state_id FROM assets WHERE id = $1 AND deleted_at IS NULL
`

type GetAssetSensitivityDomainRow struct {
	OwnerUserRef *int64      `json:"owner_user_ref"`
	StateID      pgtype.UUID `json:"state_id"`
}

// The executor needs the asset's workflow domain to resolve a state
// code, and its owner for a notify subject. One read covers both.
func (q *Queries) GetAssetSensitivityDomain(ctx context.Context, id pgtype.UUID) (GetAssetSensitivityDomainRow, error) {
	row := q.db.QueryRow(ctx, getAssetSensitivityDomain, id)
	var i GetAssetSensitivityDomainRow
	err := row.Scan(&i.OwnerUserRef, &i.StateID)
	return i, err
}

const getPendingAuthorPostPublication = `-- name: GetPendingAuthorPostPublication :one
SELECT id, action, target_kind, target_id, params, scheduled_for,
       state, error, created_by, created_at, executed_at, origin
FROM scheduled_actions
WHERE origin = 'author'
  AND action = 'change_state'
  AND target_kind = 'post'
  AND target_id = $1
  AND created_by = $2
  AND state = 'pending'
LIMIT 1
`

type GetPendingAuthorPostPublicationParams struct {
	TargetID  string `json:"target_id"`
	CreatedBy *int64 `json:"created_by"`
}

// The one pending author schedule for a post, if the caller made it.
func (q *Queries) GetPendingAuthorPostPublication(ctx context.Context, arg GetPendingAuthorPostPublicationParams) (ScheduledAction, error) {
	row := q.db.QueryRow(ctx, getPendingAuthorPostPublication, arg.TargetID, arg.CreatedBy)
	var i ScheduledAction
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.TargetKind,
		&i.TargetID,
		&i.Params,
		&i.ScheduledFor,
		&i.State,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExecutedAt,
		&i.Origin,
	)
	return i, err
}

const getScheduledAction = `-- name: GetScheduledAction :one
SELECT id, action, target_kind, target_id, params, scheduled_for,
       state, error, created_by, created_at, executed_at, origin
FROM scheduled_actions
WHERE id = $1
`

func (q *Queries) GetScheduledAction(ctx context.Context, id pgtype.UUID) (ScheduledAction, error) {
	row := q.db.QueryRow(ctx, getScheduledAction, id)
	var i ScheduledAction
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.TargetKind,
		&i.TargetID,
		&i.Params,
		&i.ScheduledFor,
		&i.State,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExecutedAt,
		&i.Origin,
	)
	return i, err
}

const listScheduledActions = `-- name: ListScheduledActions :many
SELECT id, action, target_kind, target_id, params, scheduled_for,
       state, error, created_by, created_at, executed_at, origin
FROM scheduled_actions
WHERE ($1::text IS NULL OR state = $1::text)
  AND ($2::timestamptz IS NULL
       OR created_at < $2::timestamptz)
ORDER BY created_at DESC
LIMIT $3::integer
`

type ListScheduledActionsParams struct {
	State           *string            `json:"state"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	RowLimit        int32              `json:"row_limit"`
}

// Admin surface. Optional state filter (NULL = all states), newest
// first, with a cursor on created_at for pagination.
func (q *Queries) ListScheduledActions(ctx context.Context, arg ListScheduledActionsParams) ([]ScheduledAction, error) {
	rows, err := q.db.Query(ctx, listScheduledActions, arg.State, arg.CursorCreatedAt, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledAction
	for rows.Next() {
		var i ScheduledAction
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.TargetKind,
			&i.TargetID,
			&i.Params,
			&i.ScheduledFor,
			&i.State,
			&i.Error,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExecutedAt,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActionDone = `-- name: MarkActionDone :exec
UPDATE scheduled_actions
SET state = 'done', executed_at = NOW(), error = NULL
WHERE id = $1
`

func (q *Queries) MarkActionDone(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markActionDone, id)
	return err
}

const markActionFailed = `-- name: MarkActionFailed :exec
UPDATE scheduled_actions
SET state = 'failed', executed_at = NOW(), error = $2
WHERE id = $1
`

type MarkActionFailedParams struct {
	ID    pgtype.UUID `json:"id"`
	Error *string     `json:"error"`
}

func (q *Queries) MarkActionFailed(ctx context.Context, arg MarkActionFailedParams) error {
	_, err := q.db.Exec(ctx, markActionFailed, arg.ID, arg.Error)
	return err
}

const resolveWorkflowStateByCode = `-- name: ResolveWorkflowStateByCode :one
SELECT id FROM workflow_states
WHERE domain = $1 AND code = $2
`

type ResolveWorkflowStateByCodeParams struct {
	Domain string `json:"domain"`
	Code   string `json:"code"`
}

// change_state accepts a state CODE (per ADR 0020's "to_state":
// "archived") and resolves it to the id within a domain. Returns the id
// so the executor can call ExecAssetChangeState.
func (q *Queries) ResolveWorkflowStateByCode(ctx context.Context, arg ResolveWorkflowStateByCodeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, resolveWorkflowStateByCode, arg.Domain, arg.Code)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
